### PR TITLE
Support composer 2

### PR DESCRIPTION
**Pull request by brambaud**
### Issue links

#21 

### Description

See https://getcomposer.org/upgrade/UPGRADE-2.0.md

The only things that interest us if I read correctly is:

> PluginInterface added a deactivate (so plugin can stop whatever it is doing) and an uninstall (so the plugin can remove any files it created or do general cleanup) method.

I chose to do nothing during those new phases. Maybe we could delete the created `web-dir`? 🤷‍♂️

### CODE REVIEW

**Comment by brambaud** [comment]
~~Jobs where already stuck in `1.x` https://travis-ci.org/github/drupal-composer/drupal-paranoia/builds/739078328 🤔~~

Jobs are just really slow to start 😅

**Comment by FlorentTorregrosa** [comment]
Hello,

Thanks for the PR

**Comment by FlorentTorregrosa** [comment]
Tested on my Drupal project template https://gitlab.com/florenttorregrosa-drupal/docker-drupal-project/-/commit/5c30b3b3e968dd25ad0c864ef4bc5cbedfdee6c5 and it is OK. Thanks!

**Comment by brambaud** [comment]
@FlorentTorregrosa Thanks for the test! Glad it works elsewhere than on my projects ^^

@jkribeiro CI has been updated to:
* test with Drupal 9: `drupal-composer/drupal-project:8.x-dev` contains some dependencies that don't support composer 2 like `drupal/console`. 
* test using composer 2 and composer 1
* only keep PHP >= 7.3: PHP 7.2 security support ends at the end of the month, Drupal 9 does not officially support it and  it is consistent with https://github.com/drupal-composer/drupal-project

**Comment by emilorol** [comment]
[Allow Drupal to work with Composer 2](https://www.drupal.org/project/drupal/issues/3126566)

[Update dependencies composer/composer ^2 and composer/semver to ^3
](https://www.drupal.org/project/drupal/issues/3128631)

**Comment by brambaud** [comment]
@emilorol Could you explain why did you post those links please? 😃

**Comment by brambaud** [comment]
> [Allow Drupal to work with Composer 2](https://www.drupal.org/project/drupal/issues/3126566)
> 
> [Update dependencies composer/composer ^2 and composer/semver to ^3 ](https://www.drupal.org/project/drupal/issues/3128631)

**Comment by brambaud** [comment]
(sorry for the inconvenience.. just a miss click.. 😿 )

**Comment by jkribeiro** [comment]
Thanks guys, this is a very good start.

Regarding the new methods, I think it is fine to leave as is for now, we don't want to mess with site's web-dir if the plugin is removed. We can iterate on it later if necessary. 

I'll cut a new release.

**Pull request merged**
